### ISSUE TITLE
Diseño solución temporal microcréditos

### ISSUE THREAD

**Issue by cparadap** [AlvaroContrerasS/UDM#146]
### Tipo Servicio

* [ ] Canónico
* [ ] Orquestado
* [ ] Auto-Orquestado
* [ ] WebService
* [ ] B2B

### Descripcion

1.	Borrar las siguientes colas de los broker de NBL:

i.	PDFENCRIPT.RETRY.IN
ii.	PDFSTAMP.RETRY.IN
iii.	MAILDELIVERY.RETRY.IN
iv.	INSERTRDO.RETRY.IN
v.	UPDATEDOC.RETRY.IN

2.	Crear las mismas colas en el gateway de CMM  - NBL.
3.	Crear un MPGW en Datapower que tome el mensaje y lo deje en el gateway CMM – TP
4.	Sacar las colas mencionadas de los cluster de touchpoint en los broker donde NO corre el reintentador.

**Comment by gpuglisevich** [comment]
a la espera de respuesta por parte de Banco.
