### ISSUE TITLE
BESTADO-420 - Célula Autenticación

### ISSUE THREAD

**Issue by cparadap** [AlvaroContrerasS/UDM#192]
### Tipo Servicio

* [ ] Canónico
* [ ] Orquestado
* [ ] Auto-Orquestado
* [ ] WebService
* [ ] B2B

### Descripcion

Generación de solicitud para los Labels:

20180531_CEL_AUTENTIFICACION_ES_MB_DP
20180531_CEL_AUTENTIFICACION_TR_DP
20180531_CEL_AUTENTIFICACION-WS-DP

**Comment by fabricaintegracionibm** [comment]
jueves 31-05-2018 18:22

Se generan solicitudes 709669, 709670 y 709671para  Célula Autenticación
