### ISSUE TITLE
Solicitud de PAP - Canal 43

### ISSUE THREAD

**Issue by AlvaroContrerasS** [AlvaroContrerasS/UDM#194]
### Tipo Servicio

* [ ] Canónico
* [ ] Orquestado
* [ ] Auto-Orquestado
* [ ] WebService
* [ ] B2B

### Descripcion

RE: ModificaR SERVICIO plmc1719, MENSAJERÍA.

**Comment by fabricaintegracionibm** [comment]
viernes 01-06-2018 15:25

Se crea label y solicitudes según la pedida, para instalación.

709797 |   | Datapower | Catalogo servicios Nuevo Canal   Contable | 20180531_NCC_MBS_ES
709799 |   | Datapower | Exposición servicios Nuevo Canal   Contable | 20180531_NCC_WS_DP
709800 |   | Datapower | Canónicos y ChannelsMapping.xml Nuevo   Canal Contable | 20180531_NCC_DP

**Comment by fabricaintegracionibm** [comment]
martes, 5 de junio de 2018 18:28

Correo enviado a Testing
alguna novedad a esta pedida de instalación.

**Comment by fabricaintegracionibm** [comment]
martes 05-06-2018 18:37

Testing (Valeria Olivares)  responde:
La solicitud 709799 está detenida la instalación, ya que contiene despliegue desde el Bus al Datapower y este tema lo está revisado las áreas de  MDW y Multicanal , debido que en el comando se debe ingresar el usuario y password del datapower, con lo cual quedaría visible para cualquier usuario con acceso a los servidores.
Alvaro,
Por favor tu apoyo con este tema, MDW aún no responde por esto

martes 05-06-2018 18:40
Alvaro Contreras:
Estimado, agradeceré si es posible continuar con la instalación, mientras de manera paralela middleware revisa el tema.

Desde nuestro punto de vista entendemos que se vea la clave por quien este ejecutando el script, pero quien lo ejecuta conoce la password de broker.

**Comment by fabricaintegracionibm** [comment]
lunes, 11 de junio de 2018 10:24
Testing 
La siguientes solicitudes fueron instaladas en el ambiente de TEST, por favor verificar y enviar evidencias.

•	709799
•	709797
•	709800
Adicionalmente, la guía de instalación fue asociada a la solicitud 709799

**Comment by fabricaintegracionibm** [comment]
lunes, 11 de junio de 2018 14:18
Estimados
Favor instalar NUEVA solicitud  710992 que reemplaza a la 709800.
Lleva las mismas piezas y adicionalmente el EstadoTemplates.xsl

**Comment by fabricaintegracionibm** [comment]
lunes, 11 de junio de 2018 14:18
Estimados
Favor instalar NUEVA solicitud 710992 que reemplaza a la 709800.
Lleva las mismas piezas y adicionalmente el EstadoTemplates.xsl

La 709800 favor rechazar, no es necesario vuelta atrás

**Comment by fabricaintegracionibm** [comment]
lunes, 11 de junio de 2018 15:11

Testing:
solicitud N° 710992  instalada en el ambiente de TEST, por favor verificar y enviar evidencias.
Adicionalmente, la solicitud N° 709800 fue rechazada.

lunes 11-06-2018 16:10
Se adjuntan evidencias desde el Proyecto, y se solicita  instalar en QA.
