### ISSUE TITLE
Prueba PLM

### ISSUE THREAD

**Issue by josearayagaldames** [AlvaroContrerasS/UDM#3]
### Nombre Servicio

Prueba PLM
### Tipo Servicio

* [X] Canónico
* [ ] Orquestado
* [ ] Auto-Orquestado
* [ ] WebService
* [ ] B2B

### Descripcion

Canónico de prueba

### Link sharepoint

xxxx

**Comment by AlvaroContrerasS** [comment]
no coincide especificación con respuesta del servicio
