### ISSUE TITLE
PLMV0737 - msChannelEnvironment 

### ISSUE THREAD

**Issue by AlvaroContrerasS** [AlvaroContrerasS/UDM#49]
### Tipo Servicio

* [ ] Canónico
* [ ] Orquestado
* [ ] Auto-Orquestado
* [ ] WebService
* [ ] B2B

### Descripcion

TRX ZPBK

**Comment by fabricaintegracionibm** [comment]
Nombre del Servicio: msChannelEnvironment
WebService: QryEnvironment
Expuesto en: http://167.28.65.55:6105/services/QryEnvironment/v1.1?wsdl

Detenido por falta de traza para caso OK.

**Comment by gpuglisevich** [comment]
Se realiza entrega preliminar por falta de datos de prueba.

msChannelEnvironment (PLMV0737).
EndPoint: http://167.28.65.55:6106/services/QryEnvironment/v1.1?wsdl

**Comment by AlvaroContrerasS** [comment]
Se envían datos de prueba

**Comment by gpuglisevich** [comment]
Se realiza entrega final del servicio funcionando correctamente en ambiente de laboratorio.

servicio msChannelEnvironment (PLMV0737).

EndPoint: http://167.28.65.55:6106/services/QryEnvironment/v1.1?wsdl
